### ISSUE TITLE
Clarification: manifest.config.mediaType defines artifact types

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/artifacts#11]
In the [approved TOB Proposal for artifacts](https://github.com/opencontainers/tob/blob/master/proposals/artifacts.md), we reference `manifest.config.mediaType` as the means by which we define a unique artifact and `layer.mediaType` used to uniquely define artifact layers.
> [OCI Artifacts Project Proposal](https://github.com/opencontainers/tob/blob/master/proposals/artifacts.md#contents)  
> *2. **registry operators and vendors** - guidance for how operators and vendors can support new artifact types, including how they can opt-in or out of well known artifact types.  
Registry operators that already implement `media-type` filtering will not have to change. The artifact repo will provide context on how new `media-type`s can be used, and how `media-type`s can be associated with a type of artifact.*

## Vote on Clarification
Maintainer approval
- [x] @dmcgowan 
- [x] @stevelasker
- [x] @mikebrow
- [x] @stevvooe

This issue is a clarification to be used in subsequent **how-to** content and the pending artifacts spec.

Specifically:
* `manifest.config.mediaType` defines unique artifact types
* `layer.mediaType` defines artifact layers

### OCI Meeting Notes References:

* [OCI Hackmd July 17, 2019 notes:](https://hackmd.io/El8Dd2xrTlCaCG59ns5cwg#Notes5)
> * At the top of the artifacts explain the index and manifest defintions
> * Within the repo have a collection of exsting artifacts, including the image spec mediaTypes, similar to the [PR on distribution](https://github.com/opencontainers/distribution-spec/diffs/9?base_sha=c57467233fa618002b54132db7da5ae6141bcc1f&commentable=true&head_user=AzureCR&pull_number=65&sha1=c57467233fa618002b54132db7da5ae6141bcc1f&sha2=b38feb3e095c394b56a632d1663a3db8e6765767&short_path=ae3f77d&unchanged=expanded&utf8=%E2%9C%93#defining-artifact-types)  
> "*Artifacts are defined by setting the `manifest.config.mediaType` to a globally unique value. The following format is used to differentiate the type of artifact:  
> `application/vnd.`[org|company]`.`[objectType]`.`[optionalSubType]`.config.`[version]`+json`*

### [Helm registry](https://v3.helm.sh/docs/topics/registries/) & [Singularity push](https://sylabs.io/guides/3.1/user-guide/cli/singularity_push.html) as reference implementations.

* Helm references:
  * [`manifest.config.mediaType = "application/vnd.cncf.helm.config.v1+json"`](https://github.com/helm/helm/blob/dev-v3/internal/experimental/registry/constants.go#L21) reference
  * [`layer.mediaType = "application/vnd.cncf.helm.chart.content.layer.v1+tar"`](https://github.com/helm/helm/blob/dev-v3/internal/experimental/registry/constants.go#L24) reference
  * [ORAS](https://github.com/helm/helm/blob/dev-v3/internal/experimental/registry/cache.go#L31) reference to support OCI Artifacts
* Singularity references:
  * [`manifest.config.mediaType = "application/vnd.sylabs.sif.config.v1+json"`](https://github.com/sylabs/singularity/blob/master/internal/pkg/oras/oras.go#L38) reference
  * [`layer.mediaType = "appliciation/vnd.sylabs.sif.layer.tar"`](https://github.com/helm/helm/blob/dev-v3/internal/experimental/registry/constants.go#L24) reference
  * [ORAS](https://github.com/sylabs/singularity/blob/master/internal/pkg/oras/oras.go#L6) reference to support OCI Artifacts

**Comment by mikebrow** [comment]
just added a vote list..

**Comment by dmcgowan** [comment]
This looks correct and I agree with the clarification...
but...
I still have some concern about how CNAB is making use of the spec. I saw some work to add an optional config to OCI index to allow having that definition at the index layer as well. The current problem is that if the artifact type is in the manifest and not in the index, types which use other manifests are not well represented.

**Comment by SteveLasker** [comment]
Thanks Derek,
I’d consider CNAB being mostly in a state of flux related to mediaTypes. I’ve been talking with Radu. This is mostly due to the lack of index.config support. As a result, he’s storing the CNAB config as a manifest artifact. We need more thought on this, which is why the current artifacts prs only refer to manifests. The index work will require a rev of something, so we’ve been deferring it to a next level conversation once we get the base for Helm, Singularity, OPA and some others solid. There’s a few other registries that are waiting for this to hit a complete state for these artifacts. CNAB registry spec will continue.

**Comment by vsoch** [comment]
hey @SteveLasker is there a reason the second Singularity reference ("appliciation/vnd.sylabs.sif.layer.tar") points to a Helm reference?

**Comment by SteveLasker** [comment]
To prove I’m human and demonstrate the value of PRs 🙄. I’ll fix later today.

**Comment by vsoch** [comment]
Ah good! I was totally convinced you were a robot :robot: :)

**Comment by SteveLasker** [comment]
and why you shouldn’t press button on a phone, geeze

**Comment by vsoch** [comment]
Which btw, would have been totally okay too. :)

**Comment by jonjohnsonjr** [comment]
@SteveLasker can you explain the `layer.config.mediaType` syntax in your PR description? Layers don't have a `config` property in their descriptors or in the layer themselves, so where would that `mediaType` actually go?

**Comment by SteveLasker** [comment]
@jonjohnsonjr - sorry, not `config`, just `layer.mediaType`:  https://github.com/SteveLasker/artifacts/blob/artifact-authors-how-to/authoring-artifacts.md#defining-layer-types
Here's an example for pushing a some text files with [ORAS](https://github.com/deislabs/oras)
```json
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.unknown.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.txt",
      "digest": "sha256:b869b02df9f607e50536cb7fc2037e27e786d6bbc7481be25b99c4a6505768ef",
      "size": 8,
      "annotations": {
        "org.opencontainers.image.title": "layer1.txt"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.txt",
      "digest": "sha256:35a70bc07ae77abc9970cc9234efddfc47545e85369cce75297673ba99edc32b",
      "size": 15,
      "annotations": {
        "org.opencontainers.image.title": "layer2.txt"
      }
    }
  ]
}
```

**Comment by stevvooe** [comment]
I think this encodes what we intend. At minimum, a mediaType must encode the representation of the artifact (json, protobuf, encryption, compression, etc.). We should call out that this is a many to one relationship, in that you might have multiple mediaTypes representing the same content or similarly encoded content, but their handling may differ due to the mediaType. One example is the docker and oci mediatypes for indexes. They are identical formats, handling and meaning but have different mediaTypes. Another, contrived example, might be a format that uses regular OCI layers, compatible in format, but are interpreted differently by the format.

**Comment by SteveLasker** [comment]
Yes, these are the details of what the values might represent. For the purpose of this clarification, we're agreeing we're using `manifest.config.mediaType` to define the artifact type, and `layer.mediaType` to define the layer type.

**Comment by SteveLasker** [comment]
Closing the issue as agreed and resolved. I'll work on updating the structure of the PRs to include a `spec.md` that reflects how to define and use the `mediaTypes`
