### ISSUE TITLE
Spec for how to upload `artifactType.json` and discover supported types

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/artifacts#14]
Capturing a request for how registry operators and registry vendors can upload the `artifactType.json` schema. And, how the distribution-spec would present the supported types.
The list of supported types might be per repo, or per registry.
This would ultimately be a spec enhancement (PR) on distribution, but tracking here as part of artifacts.

**Comment by mikebrow** [comment]
Suggest reopening on distribution..

**Comment by mikebrow** [comment]
closing for now due to pending archive action.. pls reopen if archive is not completed and/or if you believe this close to be in error
