### ISSUE TITLE
Provide clear definition of what is an "artifact"

### ISSUE THREAD

**Issue by Silvanoc** [opencontainers/artifacts#32]
There's no clear definition about what's an **artifact**, although the meaning can be found when reading the specification. It's nevertheless meaningful having a clear [definition](https://github.com/opencontainers/artifacts/blob/master/definitions-terms.md), because the term "artifact" is extremely overloaded.

I tend to call the files of an artifact "artifacts" themselves and then started calling the artifact "artifact set", until realizing the nonsense. But it should illustrate the need for a clear statement of what is an artifact.

What probably also makes it misleading is the plural in the name: artifacts. There's the _OCI Image Specification_ (notice the singular in the name) and the _OCI ArtifactS Specification_ (notice the plural), what sounds like specifying how to use a registry to store an "artifact set or bundle" containing multiple artifacts.

**Comment by SteveLasker** [comment]
Hi @Silvanoc,
Just pruning issues. I agree artifact(s), plural is a good question, not sure what action we'd take. 
To your point, you could push a collection of artifacts (files) as one or more blobs/layers, within a single manifest. The approach is more about pushing|pulling _an_ artifact to a registry. 

Does the latest update to the [distribution-spec](https://github.com/opencontainers/distribution-spec) help? Open to suggestions on what we'd add.

**Comment by Silvanoc** [comment]
IMO the naming issue cannot be fixed now, and it's not that it important that it needs fixing. It simply contributes to the confusion: what is an artifact? each single file you can store? each set of files referenced by a manifest?

If you look at [ORAS documentation](https://oras.land/cli/1_pushing/#pushing-artifacts-with-multiple-files) then you realize what it means (roughly speaking a set of files being referenced by a manifest). What shows that a definition in the [definitions section](https://github.com/opencontainers/artifacts/blob/master/definitions-terms.md) is needed. I can try to contribute one, but since I'm not a native speaker, it might result in a weird formulation :slightly_smiling_face:

**Comment by SteveLasker** [comment]
Thanks @Silvanoc, let me see if I can make some proposed tweaks.

**Comment by Silvanoc** [comment]
> I completely agree with your points about the evolved naming and it is confusing. I view this thread as a means to clarify these.
> There are inconsistencies across the various specs as they've been written at different times, where the use-cases have evolved. But, to be fair to the original designers of the distribution spec, the intent of the distribute-spec was to distribute anything through a CAS model. The work done by the OCI Artifacts and ORAS Artifact-spec maintainers was possible because of this forward-thinking design of the distribution-spec.

As a developer myself I can fully understand it. Keeping consistency among projects written on different times is very difficult to accomplish.

I don't pretend to blame anybody. Only to bring the inconsistencies to the surface. Since as an engineer/architect I know how important clarity and terminology are.

> I actually think this discussion is super helpful to help create some clarity.

I hope so and I'm glad that you see it so.

> Can you explain why you think ORAS has a misuse?

Perhaps "misuse" is too negative. What I mean is that the distribution specification hasn't been written from scratch, but derived from a software that was originally written to handle container images and not artifacts. The generalization from "specification for the distribution of container images" to "specification for the distribution of artifacts" isn't easy to accomplish while the names existing for historical reasons (e.g. layers) are kept. And I see keeping backwards compatibility as a very good decision.

> Minor clarification: tags aren't actually mandatory.

You're right. I rather meant either a digest or a tag (being the tag 'latest' if nothing is specified). The tag or digest in the end gives versioning support (not necessarily as numerical versions).

> As to, "what is an artifact": I'd suggest it's the thing a user wants to focus on. All the details around blobs, layers, annotations, signatures, scan results, sboms are supporting information, to that primary artifact. The end-user wants to push, discover, verify, pull, delete an artifact.

I agree on this. My initial intention was to focus only on what is an "artifact", but trying to understand the whole I've fallen down the rabbit hole...

Let me try to write a couple of small PRs with formulation proposals here and there.

**Comment by Silvanoc** [comment]
Although I've touched varied concepts and definitions in this issue. I've provided PR #50 focusing on its original goal. I don't expect it to be accepted on the first try, but I'd prefer to move the discussion from this thread to that concrete proposal to better focus it.

I might open separate issues for the different inconsistencies I've found (many of them on other projects) trying to understand what is an artifact.

**Comment by SteveLasker** [comment]
> And I see keeping backwards compatibility as a very good decision.

Agreed. Can you call out where you think backwards compact is a challenge? 

> I agree on this. My initial intention was to focus only on what is an "artifact", but trying to understand the whole I've fallen down the rabbit hole...
> Let me try to write a couple of small PRs with formulation proposals here and there.

I think the discussion really helps surface some things that can be clarifed.

As for the overall design, I'd pull @stevvooe, @dmcgowan, @vbatts, @mikebrow in as some of the original folks that could add more context.

**Comment by mikebrow** [comment]
wrt this repo.. opencontainers/artifacts currently means "an OCI repository for Artifact Guidance Documents"

**Comment by mikebrow** [comment]
yes I missed some.. we can work them in your pr.. Will be away for a couple weeks will review help define them when I get back. Cheers!

**Comment by Silvanoc** [comment]
I find the `artifact` definition of the distro spec very good, but it probably needs to be changed to accommodate to the artifacts specification, by removing the need of having a config file (as already remarked by @SteveLasker in [this comment](https://github.com/opencontainers/artifacts/pull/50#issuecomment-961208659)

Additionally it's unclear if 'image indexes' are somehow covered by any of the definitions. It'll become a more obvious problem once [the future scope of the artifacts spec](https://github.com/opencontainers/artifacts/blob/d9afcdd395525fb59ebb1dc4e27aa63a97f4b606/artifact-authors.md#future-scope) has become present.

**Comment by vbatts** [comment]
On 05/11/21 09:52 -0700, Silvano Cirujano Cuesta wrote:
>I find the `artifact` definition of the distro spec very good, but it probably needs to be changed to accommodate to the artifacts specification, by removing the need of having a config file (as already remarked by @SteveLasker in [this comment](https://github.com/opencontainers/artifacts/pull/50#issuecomment-961208659)
>
>Additionally it's unclear if 'image indexes' are somehow covered by any of the definitions. It'll become a more obvious problem once [the future scope of the artifacts spec](https://github.com/opencontainers/artifacts/blob/d9afcdd395525fb59ebb1dc4e27aa63a97f4b606/artifact-authors.md#future-scope) has become present.

The name image-index was never good. "manifest-list" was much better.

**Comment by mikebrow** [comment]
Mission for artifacts is moving to the image and distribution specifications.. and this repo is being archived. I you believe more is needed please reopen in image or distribution!
