### ISSUE TITLE
Mixing "manifests" and "layers" in an artifact?

### ISSUE THREAD

**Issue by Silvanoc** [opencontainers/artifacts#33]
I understand that [support for "artifact indexes"](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md#future-scope) similar to "image indexes" is expected to come in the future.

The [OCI image specification](https://github.com/opencontainers/image-spec) doesn't support mixing _image references_ (the [`manifests` list of an image index](https://github.com/opencontainers/image-spec/blob/master/image-index.md#image-index-property-descriptions)) with _image payload_ and _image config_ (the [`config` and `layers` list of an image manifest](https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest-property-descriptions)). Is it planed to make the _OCI artifacts specification_  drift a bit from it allowing a mixture of both?

The use-case how I came to this is following. An artifact consists of:

- A configuration file (`config` in a manifest).
- Some files (`layers` in a manifest).
- A container image (`manifests` in an index).

But in general the idea is that an artifact can have it's own files and references to other artifacts (being a container image a special artifact type), being the artifacts tools capable of handle the referred artifacts as part of the artifact itself... For example, push/pull an artifact including all referred artifacts.

Of course you can put an image name or artifact name in the configuration and then recursively resolve those references, but having it all integrated makes the management much easier.

**Comment by SteveLasker** [comment]
Hi @Silvanoc,
These are well-timed discussions.
Please see #29 with example usage at: https://github.com/deislabs/oras/blob/prototype-2/docs/artifact-manifest.md
Also, see Justins "One Manifest to Rule Them All" WIP proposal: #37

**Comment by mikebrow** [comment]
Hello I believe these questions are resolved in the release candidate versions of the image and distribution spec which are adding support for artifacts.. see new referrers api and changes to image/index.  If still have questions suggest opening an issue in image/distribution or chat it up on slack.
