### ISSUE TITLE
Branch for the OCI Artifact Reference Types working group

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/artifacts#42]
Tracking for the creation of a branch titled `reference-types` under the [oci-artifacts project](https://github.com/opencontainers/artifacts/)

This branch would provide an open and transparent location for the incubation and validation of the [working group to store artifact reference types within registries](https://github.com/opencontainers/tob/issues/96). 

The `/artifacts/tree/reference-types` branch provides a vendor-neutral location for such incubations, fostering collaborative feedback for registries to implement reference type artifacts. This working group will strive to move these goals forward while gaining experience and valuable user feedback.

**Comment by mikebrow** [comment]
SGTM

**Comment by josephschorr** [comment]
SGTM as well

**Comment by dmcgowan** [comment]
SGTM

**Comment by vbatts** [comment]
judging by the quickness of this issue, agreement, and closure, there must have been conversation about what's going on here. I'm guessing it is _only_ to have a git branch to iterate on #29 without merging into master?

**Comment by SteveLasker** [comment]
correct
