### ISSUE TITLE
Add localized strings and icons for artifact types

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/artifacts#45]
Capture how artifact authors can provide localized strings and logos for how their artifact can be visualized in registry specific tooling. 
This surfaces the details captured here: https://github.com/opencontainers/artifacts/blob/f9710ad60b6de311843df88d8f8fa1e6d0d44b50/authoring-artifacts.md#optional-publishing-the-artifact-type

**Comment by mikebrow** [comment]
Would you like to move this one over into the image or distribution spec so it doesn't get lost in the shuffle?

**Comment by mikebrow** [comment]
closing for now due to pending archive action.. pls reopen if archive is not completed and/or if you believe this close to be in error
