### ISSUE TITLE
Add clarity when `config` should be used in the `mediaType`

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/artifacts#60]
We initially focused on putting `config` in the mediaType, and including a `+json` on the extension, simply as momentum for how they were represented at the time.  
  We later clarified `config` should be reserved when there's actually a config object, and the `+json|+yaml` should be reserved to represent how the optional `config` **blob** is formatted. 

The current docs at [Defining a Unique Artifact Type](https://github.com/opencontainers/artifacts/blob/main/artifact-authors.md#defining-a-unique-artifact-type) don't clarify `config`, and show examples of using `config`, even though no config object is actually used.

TODO: 
Add clarity to define an artifact type with a shortened string, only including `config` in the string if an actual config object is represented, including `+json|+yaml|+txt` to represent the actually config formatting.

**Comment by mikebrow** [comment]
needs to consider if this is ready to close or reopen in the image spec

**Comment by mikebrow** [comment]
closing for now due to pending archive action.. pls reopen if archive is not completed and/or if you believe this close to be in error
