### ISSUE TITLE
Need a Working Group for Updating the OCI distribution-spec 

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/artifacts#9]
The [TOB approved](https://github.com/opencontainers/tob/blob/master/proposals/artifacts.md) the following project:

- Update the [OCI distribution-spec][distribution-spec] to generically reference [OCI manifest][image-manifest] and [OCI index][image-index], with [OCI Image][image-spec] as one of many artifact types it can store. 

Just opening up an issue on this to track progress...

**Comment by SteveLasker** [comment]
V1 of Distribution Spec reflects artifacts: https://github.com/opencontainers/distribution-spec#distributing-oci-images-and-other-content
